const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#labCanvas'),ctx=canvas.getContext('2d');
const S={mode:null,tool:null,hints:0,tries:0,discoveries:new Set(),field:false,hidden:false,paused:false,objects:[],drag:null,creatorMode:'edit',creatorVerified:false,polls:{yes:0,no:0,unsure:0},fair:{distance:90,records:[]}};
const TOOLS={
 explore:{kicker:'实验 01',title:'磁力探索桌',mission:'找出哪些材料会被磁铁吸引',prompts:['哪些物件看起来像金属？','金属外观一定代表会被吸引吗？','你能根据材料预测新物件吗？']},
 poles:{kicker:'实验 02',title:'磁极谜题场',mission:'让两块磁铁靠近，但不能直接拖到一起',prompts:['现在面对面的两个磁极是什么？','怎样只改变一个磁铁的方向？','运动结果支持你的预测吗？']},
 fair:{kicker:'实验 03',title:'公平实验室',mission:'只改变距离，比较能吸起的回形针数量',prompts:['这两次实验只改变了什么？','怎样让比较更公平？','一次结果足够下结论吗？']},
 create:{kicker:'实验 04',title:'挑战创造工坊',mission:'设计并亲自通过一项磁力挑战',prompts:['玩家必须使用哪条磁铁规律？','挑战有不止一种解法吗？','别人能看懂起点和终点吗？']}
};
const materials={iron:{name:'铁螺栓',mat:'铁',mag:.95,shape:'bolt'},steel:{name:'钢回形针',mat:'钢',mag:.9,shape:'clip'},aluminium:{name:'铝片',mat:'铝',mag:0,shape:'disc'},copper:{name:'铜线',mat:'铜',mag:0,shape:'wire'},wood:{name:'木块',mat:'木',mag:0,shape:'wood'},plastic:{name:'塑料尺',mat:'塑料',mag:0,shape:'ruler'},glass:{name:'玻璃珠',mat:'玻璃',mag:0,shape:'ball'}};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1700)}
function view(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+name+'View').classList.add('active');window.scrollTo(0,0)}
function updateStats(){$('#tryCount').textContent=S.tries;$('#discoverCount').textContent=S.discoveries.size;$('#hintLevel').textContent=S.hints;$('#tTries').textContent=S.tries;$('#tHints').textContent=S.hints;$('#tDiscoveries').textContent=S.discoveries.size;$('#tTool').textContent=S.tool?TOOLS[S.tool].title:'未开始'}
$$('[data-mode]').forEach(b=>b.onclick=()=>{S.mode=b.dataset.mode;$('#modeChip').textContent=S.mode==='classroom'?'课堂投影模式':'家庭探索模式';$('#teacherOpen').hidden=S.mode!=='classroom';view('hub')});
$$('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));
$$('[data-tool]').forEach(b=>b.onclick=()=>loadTool(b.dataset.tool));
function loadTool(tool){S.tool=tool;S.hints=0;S.tries=0;S.discoveries=new Set();S.drag=null;S.hidden=false;S.creatorVerified=false;const t=TOOLS[tool];$('#workspaceKicker').textContent=t.kicker;$('#workspaceTitle').textContent=t.title;$('#missionText').textContent=t.mission;view('workspace');setupTool();updateStats()}
function setupTool(){if(S.tool==='explore')setupExplore();if(S.tool==='poles')setupPoles();if(S.tool==='fair')setupFair();if(S.tool==='create')setupCreate();renderTray();renderControls()}
function obj(type,x,y,extra={}){return {type,x,y,vx:0,vy:0,r:28,angle:0,...extra}}
function magnet(x,y,angle=0,lock=false){return obj('magnet',x,y,{w:150,h:54,r:72,angle,lock,strength:1})}
function setupExplore(){S.objects=[magnet(480,115),obj('item',160,255,{key:'iron'}),obj('item',330,420,{key:'steel'}),obj('item',540,295,{key:'aluminium'}),obj('item',735,420,{key:'wood'}),obj('item',810,235,{key:'plastic'}),obj('item',650,500,{key:'copper'})]}
function setupPoles(){S.objects=[magnet(275,300,0,true),magnet(690,300,Math.PI,false),obj('target',480,300,{r:60,label:'让磁铁在圆内靠近'})]}
function setupFair(){S.fair={distance:90,records:[]};S.objects=[magnet(480,150,Math.PI/2,true),...Array.from({length:6},(_,i)=>obj('clip',390+i*36,390,{r:16,index:i}))]}
function setupCreate(){S.creatorMode='edit';S.objects=[magnet(250,260),obj('steelBall',470,310,{r:24}),obj('goal',760,310,{r:48}),obj('wall',520,165,{w:34,h:150,r:40})]}
function renderTray(){const c=$('#trayContent');if(S.tool==='explore'){c.innerHTML='<button class="tray-item" data-add="item"><span class="swatch">＋</span><span><b>随机物件</b><small>加入实验桌</small></span></button>'}else if(S.tool==='poles'){c.innerHTML='<button class="tray-item" data-action="rotate"><span class="swatch">↻</span><span><b>旋转磁铁</b><small>每次转 180°</small></span></button><button class="tray-item" data-action="release"><span class="swatch">▶</span><span><b>释放观察</b><small>让磁力行动</small></span></button>'}else if(S.tool==='fair'){c.innerHTML='<button class="tray-item" data-action="record"><span class="swatch">▦</span><span><b>记录结果</b><small>加入比较表</small></span></button>'}else{c.innerHTML='<button class="tray-item" data-add="magnet"><span class="swatch">N S</span><span><b>条形磁铁</b><small>拖进实验桌</small></span></button><button class="tray-item" data-add="steelBall"><span class="swatch">●</span><span><b>钢珠</b><small>挑战物件</small></span></button><button class="tray-item" data-add="wall"><span class="swatch">▮</span><span><b>障碍</b><small>改变路线</small></span></button><button class="tray-item" data-add="goal"><span class="swatch">◎</span><span><b>终点</b><small>设定目标</small></span></button>'}
 c.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addObject(b.dataset.add));c.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action))}
function renderControls(){const c=$('#bottomControls');if(S.tool==='explore')c.innerHTML='<button class="selected" id="labels">显示材料标签</button><button id="shuffle">换一组位置</button>';if(S.tool==='poles')c.innerHTML='<button id="rotateBtn">旋转右边磁铁</button><button class="primary" id="releaseBtn">释放观察</button>';if(S.tool==='fair')c.innerHTML='<label>距离 <input id="distanceRange" type="range" min="30" max="210" value="90"><b id="distanceValue">9 cm</b></label><button class="primary" id="recordBtn">测试并记录</button><button id="recordsBtn">查看记录</button>';if(S.tool==='create')c.innerHTML='<button class="selected" id="editBtn">编辑挑战</button><button class="primary" id="testBtn">试玩验证</button><button id="saveChallenge" disabled>保存挑战</button>';
 if($('#shuffle'))$('#shuffle').onclick=()=>{setupExplore();S.tries++;updateStats()};if($('#rotateBtn'))$('#rotateBtn').onclick=()=>action('rotate');if($('#releaseBtn'))$('#releaseBtn').onclick=()=>action('release');if($('#distanceRange'))$('#distanceRange').oninput=e=>{$('#distanceValue').textContent=Math.round(e.target.value/10)+' cm';S.fair.distance=+e.target.value;S.objects[0].y=320-S.fair.distance};if($('#recordBtn'))$('#recordBtn').onclick=recordFair;if($('#recordsBtn'))$('#recordsBtn').onclick=showRecords;if($('#editBtn'))$('#editBtn').onclick=()=>creatorMode('edit');if($('#testBtn'))$('#testBtn').onclick=()=>creatorMode('test');if($('#saveChallenge'))$('#saveChallenge').onclick=saveChallenge}
function addObject(type){S.tries++;if(S.tool==='explore'){const keys=Object.keys(materials),key=keys[Math.floor(Math.random()*keys.length)];S.objects.push(obj('item',200+Math.random()*560,220+Math.random()*260,{key}))}else if(type==='magnet')S.objects.push(magnet(260+Math.random()*300,220));else if(type==='steelBall')S.objects.push(obj('steelBall',400,320,{r:24}));else if(type==='goal')S.objects.push(obj('goal',760,320,{r:48}));else S.objects.push(obj('wall',520,220,{w:34,h:140,r:38}));updateStats()}
function action(a){if(a==='rotate'){const magnets=S.objects.filter(o=>o.type==='magnet'&&!o.lock),m=magnets[magnets.length-1];if(m){m.angle=(m.angle+Math.PI)%(Math.PI*2);S.tries++;toast('磁极方向已改变')}}if(a==='release'){S.tries++;const [a,b]=S.objects.filter(o=>o.type==='magnet'),sameFacing=Math.cos(a.angle-b.angle)<0;if(sameFacing){b.vx=3.5;S.discoveries.add('repel');toast('相同磁极互相推开')}else{b.vx=-3.5;S.discoveries.add('attract');toast('不同磁极互相吸近')}updateStats()}}
function creatorMode(mode){S.creatorMode=mode;$('#editBtn').classList.toggle('selected',mode==='edit');$('#testBtn').classList.toggle('selected',mode==='test');if(mode==='test'){S.tries++;toast('试玩开始：把钢珠送进终点')}else{S.objects.forEach(o=>{o.vx=0;o.vy=0});toast('返回编辑，可以继续调整')}updateStats()}
function saveChallenge(){const data={version:1,title:'我的磁力挑战',objects:S.objects.map(({type,x,y,angle,w,h,r})=>({type,x:Math.round(x),y:Math.round(y),angle,w,h,r}))};localStorage.setItem('magnet-maker-challenge',JSON.stringify(data));const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='magnet-challenge.json';a.click();URL.revokeObjectURL(a.href);toast('挑战已保存，不含姓名')}
function recordFair(){S.tries++;const d=S.fair.distance,count=Math.max(0,Math.min(6,Math.round(7-d/36+Math.random()*.8)));S.fair.records.push({distance:Math.round(d/10),count});S.discoveries.add('distance-'+Math.floor(d/70));S.objects.filter(o=>o.type==='clip').forEach((o,i)=>o.lift=i<count);toast(`这次吸起 ${count} 个回形针`);updateStats()}
function showRecords(){const rows=S.fair.records.length?S.fair.records.map((r,i)=>`第 ${i+1} 次：${r.distance} cm → ${r.count} 个`).join('<br>'):'还没有记录。先测试至少两次。';$('#canvasOverlay').innerHTML=`<div><h2>实验记录</h2><p>${rows}</p><p>${S.fair.records.length>=2?'比较时，我们只改变距离。':'至少记录两次，才能比较。'}</p><button onclick="document.querySelector('#canvasOverlay').hidden=true">返回实验</button></div>`;$('#canvasOverlay').hidden=false}
function hint(){if(!S.tool)return;S.hints=Math.min(3,S.hints+1);const hints={explore:['先看物件下面的材料名称。','外表像金属，不代表一定会被吸引。','把磁铁靠近铁螺栓和铝片，比较反应。'],poles:['看看面对面的两个字母。','相同磁极会推开，不同磁极会吸近。','旋转右边磁铁，再释放观察。'],fair:['比较记录中的距离和数量。','公平比较时，一次只改变一个条件。','保持同一磁铁和回形针，只调整距离。'],create:['先确定起点、钢珠和终点。','磁铁要靠近钢珠，才会产生明显作用。','编辑后点“试玩验证”，亲自完成才可保存。']}[S.tool];toast(hints[S.hints-1]);updateStats()}
$('#hintBtn').onclick=hint;$('#resetBtn').onclick=()=>{setupTool();S.tries++;updateStats();toast('本工作区已重置')};
function pointer(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.onpointerdown=e=>{const p=pointer(e);const candidates=[...S.objects].reverse();const o=candidates.find(o=>Math.hypot(o.x-p.x,o.y-p.y)<Math.max(o.r||25,38));if(o&&!(S.tool==='poles'&&o.lock)&&!(S.tool==='create'&&S.creatorMode==='test')){S.drag={o,dx:p.x-o.x,dy:p.y-o.y};canvas.setPointerCapture(e.pointerId);S.tries++;updateStats()}};
canvas.onpointermove=e=>{if(!S.drag)return;const p=pointer(e),o=S.drag.o;o.x=Math.max(35,Math.min(canvas.width-35,p.x-S.drag.dx));o.y=Math.max(35,Math.min(canvas.height-35,p.y-S.drag.dy));if(S.tool==='explore'&&o.type==='magnet')exploreReactions(o)};
canvas.onpointerup=e=>{S.drag=null;try{canvas.releasePointerCapture(e.pointerId)}catch(_){}};
canvas.ondblclick=e=>{const p=pointer(e),o=S.objects.find(o=>o.type==='magnet'&&Math.hypot(o.x-p.x,o.y-p.y)<80);if(o){o.angle+=Math.PI;S.tries++;updateStats()}};
function exploreReactions(m){S.objects.filter(o=>o.type==='item').forEach(o=>{const d=Math.hypot(o.x-m.x,o.y-m.y),mat=materials[o.key];if(d<150&&!o.checked){o.checked=true;S.discoveries.add(o.key);if(mat.mag){o.vx=(m.x-o.x)*.035;o.vy=(m.y-o.y)*.035;toast(`${mat.name}（${mat.mat}）被吸引`)}else toast(`${mat.name}（${mat.mat}）没有被吸引`);updateStats()}if(d>185)o.checked=false})}
function physics(){if(S.paused)return;S.objects.forEach(o=>{if(Math.abs(o.vx)>.02||Math.abs(o.vy)>.02){o.x+=o.vx;o.y+=o.vy;o.vx*=.94;o.vy*=.94}});if(S.tool==='create'&&S.creatorMode==='test'){const balls=S.objects.filter(o=>o.type==='steelBall'),mags=S.objects.filter(o=>o.type==='magnet');balls.forEach(b=>{mags.forEach(m=>{const dx=m.x-b.x,dy=m.y-b.y,d=Math.max(45,Math.hypot(dx,dy));if(d<260){const f=2400/(d*d);b.vx+=dx*f;b.vy+=dy*f}});b.x+=b.vx;b.y+=b.vy;b.vx*=.985;b.vy*=.985;S.objects.filter(o=>o.type==='wall').forEach(w=>{if(Math.abs(b.x-w.x)<(w.w/2+b.r)&&Math.abs(b.y-w.y)<(w.h/2+b.r)){b.vx*=-.8;b.vy*=-.8}});const goal=S.objects.find(o=>o.type==='goal');if(goal&&Math.hypot(b.x-goal.x,b.y-goal.y)<goal.r){S.creatorVerified=true;S.discoveries.add('verified');$('#saveChallenge').disabled=false;toast('挑战验证成功，可以保存了');creatorMode('edit')}})}}
function drawTable(){const g=ctx.createLinearGradient(0,0,0,600);g.addColorStop(0,'#cfa77d');g.addColorStop(1,'#b5885e');ctx.fillStyle=g;ctx.fillRect(0,0,960,600);ctx.strokeStyle='#6f4b2a16';for(let y=40;y<600;y+=58){ctx.beginPath();ctx.moveTo(0,y);ctx.bezierCurveTo(250,y-8,650,y+10,960,y-3);ctx.stroke()}}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke()}}
function drawMagnet(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.angle);ctx.shadowColor='#24394a55';ctx.shadowBlur=18;ctx.shadowOffsetY=10;roundRect(-75,-27,75,54,11,'#ed625a');roundRect(0,-27,75,54,11,'#3d7fc9');ctx.shadowColor='transparent';ctx.fillStyle='#fff';ctx.font='900 23px ui-monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('N',-38,1);ctx.fillText('S',38,1);ctx.restore();if(S.field)drawField(o)}
function drawField(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.angle);ctx.strokeStyle='#d9fff088';ctx.lineWidth=2;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(0,0,105+i*42,48+i*27,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawItem(o){const m=materials[o.key];ctx.save();ctx.translate(o.x,o.y);ctx.shadowColor='#263b4744';ctx.shadowBlur=10;ctx.shadowOffsetY=6;if(m.shape==='bolt'){ctx.rotate(-.6);roundRect(-8,-28,16,56,5,'#708690');roundRect(-17,-31,34,13,4,'#a9b8bd')}else if(m.shape==='clip'){ctx.strokeStyle='#5f7580';ctx.lineWidth=6;ctx.beginPath();ctx.ellipse(0,0,15,29,0,0,Math.PI*1.75);ctx.stroke()}else if(m.shape==='disc'){ctx.fillStyle='#b8c4c8';ctx.beginPath();ctx.arc(0,0,25,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#8fa0a5';ctx.stroke()}else if(m.shape==='wood'){roundRect(-30,-23,60,46,6,'#9c6339');ctx.strokeStyle='#704329';ctx.beginPath();ctx.moveTo(-22,-8);ctx.bezierCurveTo(-5,-18,8,4,22,-8);ctx.stroke()}else if(m.shape==='ruler'){roundRect(-34,-10,68,20,4,'#59b6c5');ctx.strokeStyle='#dff9fb';for(let x=-25;x<30;x+=10){ctx.beginPath();ctx.moveTo(x,-10);ctx.lineTo(x,-2);ctx.stroke()}}else if(m.shape==='wire'){ctx.strokeStyle='#b5683e';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,25,.4,Math.PI*1.8);ctx.stroke()}else{ctx.fillStyle='#d7e4e8';ctx.beginPath();ctx.arc(0,0,25,0,Math.PI*2);ctx.fill()}ctx.shadowColor='transparent';ctx.fillStyle='#17324d';ctx.font='700 14px system-ui';ctx.textAlign='center';ctx.fillText(`${m.name} · ${m.mat}`,0,48);ctx.restore()}
function drawObject(o){if(o.type==='magnet')drawMagnet(o);else if(o.type==='item')drawItem(o);else if(o.type==='target'||o.type==='goal'){ctx.save();ctx.strokeStyle=o.type==='goal'?'#53d0aa':'#fff8';ctx.lineWidth=5;ctx.setLineDash([10,9]);ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#17324d';ctx.font='800 14px system-ui';ctx.textAlign='center';ctx.fillText(o.label||'终点',o.x,o.y+5);ctx.restore()}else if(o.type==='clip'){ctx.strokeStyle='#5f7580';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(o.x,o.lift?250:o.y,8,16,0,0,Math.PI*1.8);ctx.stroke()}else if(o.type==='steelBall'){ctx.save();const g=ctx.createRadialGradient(o.x-8,o.y-8,2,o.x,o.y,27);g.addColorStop(0,'#fff');g.addColorStop(.25,'#aebfc6');g.addColorStop(1,'#455c67');ctx.fillStyle=g;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill();ctx.restore()}else if(o.type==='wall')roundRect(o.x-o.w/2,o.y-o.h/2,o.w,o.h,8,'#38546a')}
function loop(){physics();drawTable();S.objects.forEach(drawObject);requestAnimationFrame(loop)}loop();
// Teacher controls
function teacher(open){$('#teacherDrawer').classList.toggle('open',open);$('#teacherDrawer').setAttribute('aria-hidden',!open);$('#drawerScrim').hidden=!open}
$('#teacherOpen').onclick=()=>teacher(true);$('#teacherClose').onclick=()=>teacher(false);$('#drawerScrim').onclick=()=>teacher(false);$$('[data-vote]').forEach(b=>b.onclick=()=>{S.polls[b.dataset.vote]++;b.querySelector('b').textContent=S.polls[b.dataset.vote]});$('#clearPoll').onclick=()=>{S.polls={yes:0,no:0,unsure:0};$$('[data-vote] b').forEach(b=>b.textContent=0)};
$('#pauseBtn').onclick=()=>{S.paused=!S.paused;$('#pauseScreen').hidden=!S.paused;$('#pauseBtn').textContent=S.paused?'恢复全班':'暂停全班';teacher(false)};$('#pauseScreen').onclick=()=>{S.paused=false;$('#pauseScreen').hidden=true;$('#pauseBtn').textContent='暂停全班'};
$('#hideResultBtn').onclick=()=>{S.hidden=!S.hidden;$('#canvasOverlay').hidden=!S.hidden;$('#canvasOverlay').innerHTML='<div><h2>先预测，再观察</h2><p>老师还没有揭示实验结果。</p></div>';$('#hideResultBtn').textContent=S.hidden?'揭示结果':'隐藏结果'};
$('#fieldBtn').onclick=()=>{S.field=!S.field;$('#fieldLegend').hidden=!S.field;$('#fieldBtn').textContent=S.field?'隐藏磁力线':'显示磁力线'};$('#discussionBtn').onclick=()=>{const p=TOOLS[S.tool]?.prompts||['你观察到什么证据？'];$('#discussionText').textContent=p[Math.floor(Math.random()*p.length)]};$('#printBtn').onclick=()=>window.print();$('#saveBtn').onclick=()=>{const result={date:new Date().toISOString(),tool:S.tool,tries:S.tries,hints:S.hints,discoveries:[...S.discoveries]};localStorage.setItem('magnet-last-session',JSON.stringify(result));toast('本次结果已保存在这台设备')};
